- name: Configure Docker
  block:
    - name: Install Docker package
      apt:
        name: docker.io
        state: present

    - name: Create systemd drop-in unit directory
      when: proxy.address
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory

    - name: Configure proxy
      when: proxy.address
      template:
        src: proxy.conf.j2
        dest: /etc/systemd/system/docker.service.d/proxy.conf
      become: yes

    - name: Restart Docker daemon
      when: proxy.address
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
  become: true
