- name: Configure git user
  shell: |
    git config --global user.name "{{ git.name }}"
    git config --global user.email "{{ git.email }}"

- name: Configure git editor
  shell: |
    git config --global core.editor "{{ git.editor }}"

- name: Add proxy config
  when: proxy.address
  template:
    src: ssh-config.j2
    dest: ~/.ssh/config
