- hosts: localhost
  environment:
    http_proxy: "http://{{ proxy.address }}"
    https_proxy: "https://{{ proxy.address }}"
    no_proxy: "{{ proxy.no_proxy }}"
  roles:
    - generate-ssh-keys
    - setup-docker
    - setup-git
    - setup-go
    - setup-vim
