- name: Install Go
  block:
    - name: Install kubectl
      get_url:
        url: 'https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl.version }}/bin/linux/amd64/kubectl'
        dest: '/usr/local/bin/kubectl'
        mode: '0755'
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Helm
      unarchive:
        src: 'https://get.helm.sh/helm-v{{ helm.version }}-linux-amd64.tar.gz'
        dest: '/usr/local/bin'
        extra_opts:
          - '--strip-components=1'
          - 'linux-amd64/helm'
        remote_src: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Minikube
      get_url:
        url: 'https://github.com/kubernetes/minikube/releases/download/v{{ minikube.version }}/minikube-linux-amd64'
        dest: '/usr/local/bin/minikube'
        mode: '0755'
      when: ansible_facts['os_family'] == 'Debian'
  become: yes
